### ISSUE TITLE
Manual addon install has led to inability to install additional addons. Also, how to reset?

### ISSUE THREAD

**Issue by q20** [ggyeh/TVML-Kodi-Addons#2]
I tried to install an addon manually; there was no indication it succeeded or failed. The addon does not appear in available addons and if I attempt to install from zip the system now errors, saying xyz.zip already exists. If I manually remove that file, another error is presented. I forget what, though. I think it could be something like xyz.zip is not found.

In an attempt to work around the xyz issue I tried resetting the application to defaults. First by removing the server from TVML, then TVML from my AppleTV and thirdly by restarting my NAS, yet my settings persist. Where are they stored? How do I completely reset the service?

**Comment by ggyeh** [comment]
Sorry for the delay.
Just release version 0.6 with a lot of fixes.
Also, there's now a section in the menu for clearing application settings. (FYI, they are stored on the client - i.e. the appleTV).
I fixed a major problem I had with leaking file descriptors which had a lot of side effects.
Please let me know if your problems are still happening in the new release.

**Comment by ggyeh** [comment]
Version 0.7 now saves all settings/config/history locally on the server.
Reset can be made via the gui (i.e. the app itself) or by deleting the ~/.TVMLSERVER directory.
Also adding repositories from zip file is fixed in 0.7.
Please reopen if problems persist.
