### ISSUE TITLE
Add from zip file not working

### ISSUE THREAD

**Issue by joelifer** [ggyeh/TVML-Kodi-Addons#3]
Hello, great work on this! I'm having an issue of trying to add a repo from a zip file and I will just get a quick flash of my root directory and then it backs out to the add from zip file menu again and retrying just repeats this over and over.

I have ran both as an executable and as a source and it gives the same error. Thank you!

**Comment by ggyeh** [comment]
Sorry for the wait.
This should be resolved in 0.7
